import type { WizardState } from "@/types";

export function generateAIContext(state: WizardState): string {
  const { project, architecture, standards, uxPatterns, designSystem } = state;

  const doNotUse: string[] = [];
  if (!project.stateManagement.includes("redux-toolkit")) doNotUse.push("Redux / Redux Toolkit");
  if (project.formLibrary !== "formik") doNotUse.push("Formik");
  if (!project.styling.includes("emotion") && !project.styling.includes("styled-components")) {
    doNotUse.push("Styled Components or Emotion (CSS-in-JS)");
  }
  if (project.validation !== "yup") doNotUse.push("Yup");
  if (project.validation !== "zod") doNotUse.push("Zod");
  if (standards.dateLibrary !== "dayjs") doNotUse.push("dayjs");
  if (standards.dateLibrary !== "date-fns") doNotUse.push("date-fns");
  if (standards.testingUnit !== "jest") doNotUse.push("Jest");
  if (standards.testingUnit !== "vitest") doNotUse.push("Vitest");

  const stateStr = project.stateManagement.length
    ? project.stateManagement.join(", ")
    : "None";

  return `# AI Context — ${project.projectName || "Project"}

This file defines all technical decisions for this project.
When generating code, follow these decisions strictly. Do not introduce unlisted dependencies.

---

## Stack

- **Framework:** ${project.framework || "Not specified"}
- **Language:** ${project.language === "typescript" ? "TypeScript — always use proper types, avoid \`any\`" : "JavaScript"}
- **Package Manager:** ${project.packageManager}

## State

- **Client state:** ${stateStr}
- **Server state:** ${project.serverState}
- **API style:** ${project.apiStyle}
- **HTTP client:** ${project.apiClient}

## Forms

- **Library:** ${project.formLibrary}
- **Validation:** ${project.validation}

## Styling

- **Primary:** ${project.styling[0] || "none"}
${project.styling.length > 1 ? `- **Secondary:** ${project.styling.slice(1).join(", ")}` : ""}

## Architecture Rules

- Folder strategy: ${architecture.folderStrategy}
- File naming: ${architecture.namingConvention}
- Path alias: ${architecture.pathAliases ? `${architecture.aliasRoot}/* → src/*` : "relative imports only"}
- Barrel files: ${architecture.barrelFiles}
- Env vars: ${architecture.envStrategy}

## Standards

- Error handling: ${standards.errorHandling}
- Retry policy: ${standards.retryPolicy}
- Unit tests: ${standards.testingUnit}
- E2E tests: ${standards.testingE2E}
- Linting: ${standards.linting.join(", ") || "none"}
- Git: ${standards.gitStrategy}
- Auth: ${standards.authApproach}
- Dates: ${standards.dateLibrary}

## UX Patterns

- Loading: ${uxPatterns.loadingPattern}
- Empty states: ${uxPatterns.emptyStateStyle}
- Success feedback: ${uxPatterns.successFeedback}
- Destructive confirmation: ${uxPatterns.confirmationPattern}

## Design Tokens

- Accent color: ${designSystem.accentColorHex}
- Neutral: ${designSystem.neutralPalette}
- Font: ${designSystem.fontFamily}
- Radius scale: ${designSystem.radiusScale}
- Spacing base: ${designSystem.spacingBase}px
- Shadows: ${designSystem.shadowDepth}

---

## Do NOT Use

The following were explicitly not chosen for this project:

${doNotUse.length > 0 ? doNotUse.map((d) => `- ${d}`).join("\n") : "- (no explicit exclusions)"}

---

## Code Generation Rules

1. Always match the naming convention: **${architecture.namingConvention}** for components
2. Import paths must use ${architecture.pathAliases ? `the \`${architecture.aliasRoot}\` alias` : "relative imports"}
3. Validate all user input with **${project.validation !== "none" ? project.validation : "manual validation"}**
4. All API errors should be handled with **${standards.errorHandling}** pattern
5. Loading states use **${uxPatterns.loadingPattern}** pattern
6. ${standards.gitStrategy === "conventional-commits" ? "Commit messages must follow Conventional Commits format (feat:, fix:, chore:)" : "No enforced commit format"}

*This file was generated by Frontend Decision Engine. Paste it into your AI assistant's context window at the start of every coding session.*
`;
}
