import type { WizardState } from "@/types";

const frameworkLabel: Record<string, string> = {
  next: "Next.js (App Router)",
  "vite-react": "Vite + React (SPA)",
  remix: "Remix",
  astro: "Astro",
  sveltekit: "SvelteKit",
};

const stateLabel: Record<string, string> = {
  zustand: "Zustand",
  "redux-toolkit": "Redux Toolkit",
  jotai: "Jotai",
  "context-only": "React Context only",
  none: "None",
};

const stylingLabel: Record<string, string> = {
  tailwind: "Tailwind CSS",
  "css-modules": "CSS Modules",
  scss: "SCSS",
  "styled-components": "Styled Components",
  emotion: "Emotion",
};

export function generateGuidelines(state: WizardState): string {
  const { project, architecture, standards, uxPatterns } = state;
  const generatedAt = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  return `# Project Guidelines

> Generated by [Frontend Decision Engine](https://github.com/your-org/frontend-decision-engine) on ${generatedAt}.
> This document is the single source of truth for architectural decisions in this project.

---

## Project Overview

- **Name:** ${project.projectName || "Unnamed Project"}
- **Framework:** ${frameworkLabel[project.framework] || "Not specified"}
- **Language:** ${project.language === "typescript" ? "TypeScript (strict mode)" : "JavaScript"}
- **Package Manager:** ${project.packageManager}

---

## Stack

### State Management

${project.stateManagement.length > 0
  ? project.stateManagement.map((s) => `- ${stateLabel[s] || s}`).join("\n")
  : "- No global client state library (use server state or React Context)"}

### Server State / Data Fetching

${project.serverState === "react-query"
  ? "- TanStack Query (React Query) — cache-first, background refetching"
  : project.serverState === "swr"
  ? "- SWR — lightweight REST-focused data fetching"
  : "- Manual fetch / RSC / no caching library"}

### API

- **Style:** ${project.apiStyle.toUpperCase()}
- **HTTP Client:** ${project.apiClient === "fetch" ? "Native Fetch API" : "Axios"}

### Forms & Validation

- **Forms:** ${project.formLibrary === "react-hook-form" ? "React Hook Form" : project.formLibrary === "tanstack-form" ? "TanStack Form" : project.formLibrary === "formik" ? "Formik" : "None (native HTML forms)"}
- **Validation:** ${project.validation === "zod" ? "Zod" : project.validation === "yup" ? "Yup" : "None"}

### Styling

${project.styling.length > 0
  ? project.styling.map((s) => `- ${stylingLabel[s] || s}`).join("\n")
  : "- No styling library configured"}

---

## Architecture

### Folder Structure

- **Strategy:** ${architecture.folderStrategy === "feature-based" ? "Feature-based (group by domain)" : architecture.folderStrategy === "layer-based" ? "Layer-based (group by type)" : "Simple / flat"}
- **File naming:** ${architecture.namingConvention}
- **Path aliases:** ${architecture.pathAliases ? `Enabled — import from \`${architecture.aliasRoot}/*\`` : "Disabled — use relative imports"}
- **Barrel files:** ${architecture.barrelFiles === "always" ? "Used everywhere (index.ts in all folders)" : architecture.barrelFiles === "feature-level-only" ? "Feature boundaries only" : "Never — use direct imports"}

### Environment Variables

${architecture.envStrategy === "schema-validated"
  ? "Schema-validated at build time using t3-env. All environment variables are typed."
  : "Standard dotenv files (.env, .env.local). No runtime validation."}

---

## Standards

### Error Handling

- **Strategy:** ${standards.errorHandling === "toast" ? "Toast notifications for all errors" : standards.errorHandling === "inline" ? "Inline field-level errors" : "Hybrid — inline for form validation, toast for API errors"}
- **Retry policy:** ${standards.retryPolicy === "none" ? "None — fail fast" : standards.retryPolicy === "manual" ? "Manual retry button shown" : "Automatic retry with backoff"}
- **Logging:** ${standards.logging === "sentry" ? "Sentry for production error tracking" : standards.logging === "console" ? "console.error in development only" : "No logging"}

### Testing

- **Unit tests:** ${standards.testingUnit === "none" ? "None" : `${standards.testingUnit.charAt(0).toUpperCase() + standards.testingUnit.slice(1)}`}
- **E2E tests:** ${standards.testingE2E === "none" ? "None" : `${standards.testingE2E.charAt(0).toUpperCase() + standards.testingE2E.slice(1)}`}

### Code Quality

- **Linting / formatting:** ${standards.linting.length > 0 ? standards.linting.join(", ") : "None configured"}
- **Git commits:** ${standards.gitStrategy === "conventional-commits" ? "Conventional Commits (feat:, fix:, chore:, docs:, refactor:)" : "No enforced format"}

### Authentication

${standards.authApproach === "none" ? "No authentication required." : standards.authApproach === "cookie" ? "Cookie-based auth (HttpOnly, Secure cookies)." : "JWT-based auth (manual implementation)."}

### Dates & Times

${standards.dateLibrary === "native" ? "Native Date API." : standards.dateLibrary === "dayjs" ? "dayjs — Moment-compatible, 2KB." : "date-fns — functional, fully tree-shakeable."}

---

## UX Patterns

| Pattern | Decision |
|---|---|
| Loading states | ${uxPatterns.loadingPattern === "skeleton" ? "Skeleton placeholders" : uxPatterns.loadingPattern === "spinner" ? "Spinner indicator" : "NProgress-style progress bar"} |
| Empty states | ${uxPatterns.emptyStateStyle === "illustration" ? "SVG illustrations" : uxPatterns.emptyStateStyle === "icon-text" ? "Icon + descriptive text" : "Text only"} |
| Success feedback | ${uxPatterns.successFeedback === "toast" ? "Toast notifications" : uxPatterns.successFeedback === "snackbar" ? "Snackbar with action" : "Redirect to success page"} |
| Destructive actions | ${uxPatterns.confirmationPattern === "modal" ? "Modal confirmation dialog" : uxPatterns.confirmationPattern === "inline" ? "Inline confirm/cancel" : "No confirmation (immediate)"} |

---

*Generated by Frontend Decision Engine. Do not edit manually — regenerate from your blueprint.*
`;
}
