import type { WizardState } from "@/types";
import { deriveTokens } from "@/tokens/derive";

const neutralScales: Record<string, Record<string, string>> = {
  zinc:  { "50":"#fafafa","100":"#f4f4f5","200":"#e4e4e7","300":"#d4d4d8","400":"#a1a1aa","500":"#71717a","600":"#52525b","700":"#3f3f46","800":"#27272a","900":"#18181b" },
  slate: { "50":"#f8fafc","100":"#f1f5f9","200":"#e2e8f0","300":"#cbd5e1","400":"#94a3b8","500":"#64748b","600":"#475569","700":"#334155","800":"#1e293b","900":"#0f172a" },
  gray:  { "50":"#f9fafb","100":"#f3f4f6","200":"#e5e7eb","300":"#d1d5db","400":"#9ca3af","500":"#6b7280","600":"#4b5563","700":"#374151","800":"#1f2937","900":"#111827" },
  stone: { "50":"#fafaf9","100":"#f5f5f4","200":"#e7e5e4","300":"#d6d3d1","400":"#a8a29e","500":"#78716c","600":"#57534e","700":"#44403c","800":"#292524","900":"#1c1917" },
};

export function generateTokensCss(state: WizardState): string {
  const tokens = deriveTokens(state.designSystem);
  const neutral = neutralScales[state.designSystem.neutralPalette] || neutralScales.zinc;

  const accentEntries = Object.entries(tokens.accent)
    .map(([k, v]) => `  --color-accent-${k}: ${v};`)
    .join("\n");

  const neutralEntries = Object.entries(neutral)
    .map(([k, v]) => `  --color-neutral-${k}: ${v};`)
    .join("\n");

  const radiusEntries = Object.entries(tokens.radius)
    .map(([k, v]) => `  --radius-${k}: ${v};`)
    .join("\n");

  const shadowEntries = Object.entries(tokens.shadow)
    .map(([k, v]) => `  --shadow-${k}: ${v};`)
    .join("\n");

  const spacingEntries = Object.entries(tokens.spacing)
    .map(([k, v]) => `  --spacing-${k}: ${v};`)
    .join("\n");

  return `/* Design Tokens — ${state.project.projectName || "Project"} */
/* Generated by Frontend Decision Engine */
/* Drop this file into your project and import it in your main CSS */

:root {
  /* ─── Accent Color Scale ──────────────────── */
${accentEntries}

  /* ─── Neutral Color Scale ────────────────── */
${neutralEntries}

  /* ─── Semantic Colors ────────────────────── */
  --color-background: var(--color-neutral-50);
  --color-surface: #ffffff;
  --color-border: var(--color-neutral-200);
  --color-text: var(--color-neutral-900);
  --color-text-muted: var(--color-neutral-500);
  --color-primary: var(--color-accent-500);
  --color-primary-hover: var(--color-accent-600);
  --color-success: #22c55e;
  --color-warning: #f59e0b;
  --color-danger: #ef4444;

  /* ─── Typography ─────────────────────────── */
  --font-sans: ${tokens.fontFamily};
  --font-mono: ui-monospace, 'Cascadia Code', 'Source Code Pro', monospace;

  /* ─── Radius ─────────────────────────────── */
${radiusEntries}

  /* ─── Shadow ─────────────────────────────── */
${shadowEntries}

  /* ─── Spacing ────────────────────────────── */
${spacingEntries}
}
`;
}
